---
- hosts: target
  become: yes
  gather_facts: true
  tasks:
  - name: Checking if port 22 is enabled
    wait_for: "host={{ inventory_hostname }} port=22 timeout=60"
    delegate_to: localhost
    
    
    